services:
  db:
    image: frankframework.org/frank-manual/src-steps/frank-2-transactions/postgresql
    build: ./db
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: testiaf_user00
      POSTGRES_USER: testiaf_user
      POSTGRES_DB: testiaf
  jms:
    image: apache/activemq-artemis:2.36.0
    ports:
      - 8160:8160
      - 8092:61616
    environment:
      ANONYMOUS_LOGIN: true
  ff:
    image: frankframework/frankframework:latest
    ports:
      - 8090:8080
    volumes:
      - ./src/main/resources:/opt/frank/resources
      - ./drivers:/opt/frank/drivers
    environment:
      jdbc.hostname: db
      jms.hostname: jms
      transactionmanager.type.default: NARAYANA
      jms.createDestination: true
